//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToursApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int Id { get; set; }
        public string EmployeeName { get; set; }
        public string Position { get; set; }
        public Nullable<System.DateTime> Month { get; set; }
        public Nullable<int> ToursCompleted { get; set; }
        public Nullable<int> ToursBooked { get; set; }
        public Nullable<int> ClientsServed { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string Name { get; set; }
        public string Download { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
